In [1]:
import os
import librosa
import numpy as np
import librosa

In [4]:
for subdir,dirs,files in os.walk('audio_data/ambulance/'):
    for filename in files:
        filepath=subdir+os.sep+filename
        if filepath.endswith('webm'):
            print(filepath)

audio_data/ambulance/\Ambulance_1.webm
audio_data/ambulance/\Ambulance_10.webm
audio_data/ambulance/\Ambulance_11.webm
audio_data/ambulance/\Ambulance_12.webm
audio_data/ambulance/\Ambulance_13.webm
audio_data/ambulance/\Ambulance_14.webm
audio_data/ambulance/\Ambulance_15.webm
audio_data/ambulance/\Ambulance_16.webm
audio_data/ambulance/\Ambulance_18.webm
audio_data/ambulance/\Ambulance_19.webm
audio_data/ambulance/\Ambulance_2.webm
audio_data/ambulance/\Ambulance_20.webm
audio_data/ambulance/\Ambulance_21.webm
audio_data/ambulance/\Ambulance_22.webm
audio_data/ambulance/\Ambulance_23.webm
audio_data/ambulance/\Ambulance_24.webm
audio_data/ambulance/\Ambulance_25.webm
audio_data/ambulance/\Ambulance_26.webm
audio_data/ambulance/\Ambulance_28.webm
audio_data/ambulance/\Ambulance_29.webm
audio_data/ambulance/\Ambulance_3.webm
audio_data/ambulance/\Ambulance_5.webm
audio_data/ambulance/\Ambulance_6.webm
audio_data/ambulance/\Ambulance_7.webm
audio_data/ambulance/\Ambulance_8.webm
audio_d

In [6]:
arr=np.random.randint(low=10,high=20,size=(2,3))

In [8]:
arr

array([[11, 10, 11],
       [19, 19, 12]])

In [10]:
arr=arr.flatten()

In [11]:
arr

array([11, 10, 11, 19, 19, 12])

In [12]:
arr.reshape(2,3)

array([[11, 10, 11],
       [19, 19, 12]])

In [5]:
for subdir,dirs,files in os.walk('audio_data'):
    for filename in files:
        filepath=subdir+os.sep+filename
        if filepath.endswith('webm'):
            #print(filepath)
            if subdir=='audio_data\ambulance':
                print('inside')

audio_data\ambulance
audio_data\ambulance
audio_data\ambulance
audio_data\ambulance
audio_data\ambulance
audio_data\ambulance
audio_data\ambulance
audio_data\ambulance
audio_data\ambulance
audio_data\ambulance
audio_data\ambulance
audio_data\ambulance
audio_data\ambulance
audio_data\ambulance
audio_data\ambulance
audio_data\ambulance
audio_data\ambulance
audio_data\ambulance
audio_data\ambulance
audio_data\ambulance
audio_data\ambulance
audio_data\ambulance
audio_data\ambulance
audio_data\ambulance
audio_data\ambulance
audio_data\ambulance
audio_data\fire
audio_data\fire
audio_data\fire
audio_data\fire
audio_data\fire
audio_data\fire
audio_data\fire
audio_data\fire
audio_data\fire
audio_data\fire
audio_data\fire
audio_data\fire
audio_data\fire
audio_data\fire
audio_data\fire
audio_data\fire
audio_data\fire
audio_data\fire
audio_data\fire
audio_data\fire
audio_data\fire
audio_data\fire
audio_data\fire
audio_data\fire
audio_data\fire
audio_data\fire
audio_data\fire
audio_data\fire
audio_